Seed:  5299001979962995655
Testing 1 Robots
Solution time: 0.5261354446411133s

Testing 2 Robots
Solution time: 3.070931911468506s

Testing 3 Robots
Solution time: 3.789834499359131s

Testing 4 Robots
Process Solving:
Traceback (most recent call last):
  File "/home/salewsky/.conda/envs/Clingo2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/salewsky/.conda/envs/Clingo2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/salewsky/MAPF-Project/random_benchmark_solver.py", line 104, in solving
    with ctl.solve(yield_=True) as handle:
  File "/home/salewsky/.conda/envs/Clingo2/lib/python3.9/site-packages/clingo/control.py", line 572, in solve
    _c_call('clingo_solve_handle_t*', _lib.clingo_control_solve,
  File "/home/salewsky/.conda/envs/Clingo2/lib/python3.9/site-packages/clingo/_internal.py", line 41, in _c_call
    _handle_error(c_fun(*args, p_ret), handler)
  File "/home/salewsky/.conda/envs/Clingo2/lib/python3.9/site-packages/clingo/_internal.py", line 64, in _handle_error
    raise MemoryError(msg)
MemoryError: bad_alloc
